Use self link in service networking connection
This commit adds a network data source to the private_service_access
submodule and uses that data source to obtain the required network
attributes.

This change fixes the following issue:

> Error: Provider produced inconsistent final plan
>
> When expanding the plan for
> module.private-service-access.google_service_networking_connection.private_service_access
> to include new values learned so far during apply, provider "google-beta"
> produced an invalid new value for .network: was
> cty.StringVal("test-vpc-private-access"), but now
> cty.StringVal("https://www.googleapis.com/compute/v1/projects/test-project/global/networks/test-vpc-private-access").
>
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.